kind: Deployment
apiVersion: apps/v1
metadata:
  name: slproject
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: slearn
  template:
    metadata:
      labels:
        app: slearn
    spec:
      containers:
        - name: cont1
          image: nginx
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              cpu: 50m  ## 5% of the 1 core cpu on the vm
---
kind: Service
apiVersion: v1
metadata:
  name: slearn-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: slearn
  ports:
    - port: 80
      targetPort: 80
