apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-pvc
spec:
  storageClassName: manual
  volumeName: myapp-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
